### ISSUE TITLE
Logo Design: Coin Marketplace

### ISSUE THREAD

**Issue by baranpirincal** [AiDirex/basic-marketplace#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by aidinrs** [comment]
Hi, @baranpirincal 
That is great, It will be appreciated if you want to design a logo :+1: 
Feel free to do any help, and ask me any questions that you have.

**Comment by baranpirincal** [comment]
@AiDirex 

Hey again,

If you have an any idea about design, please share with me.

**Comment by aidinrs** [comment]
@baranpirincal a futuristic theme would be cool too.
